force-app/main/default/objects/FactoringRequest__c/FactoringRequest__c.object-meta.xml
<CustomObject>
    <label>Factoring Request</label>
    <nameField>
        <displayFormat>FREQ#{000000}</displayFormat>
        <label>Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factoring Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FactoringRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factoring Requests</relationshipLabel>
    <relationshipName>FactoringRequests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Factoring Requests</relationshipLabel>
    <relationshipName>FactoringRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/RequestID__c.field-meta.xml
<CustomField>
    <fullName>RequestID__c</fullName>
    <externalId>true</externalId>
    <label>Request ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/FactoringResponse__c.object-meta.xml
<CustomObject>
    <label>Factoring Response</label>
    <nameField>
        <displayFormat>FRES#{000000}</displayFormat>
        <label>Response #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factoring Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FactoringResponse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factoring Responses</relationshipLabel>
    <relationshipName>FactoringResponses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Factoring Responses</relationshipLabel>
    <relationshipName>FactoringResponses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/FactoringRequest__c.field-meta.xml
<CustomField>
    <fullName>FactoringRequest__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Factoring Request</label>
    <referenceTo>FactoringRequest__c</referenceTo>
    <relationshipLabel>Factoring Responses</relationshipLabel>
    <relationshipName>FactoringResponses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/PurchaseLimit__c.field-meta.xml
<CustomField>
    <fullName>PurchaseLimit__c</fullName>
    <label>Purchase Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/ReasonForDeclination__c.field-meta.xml
<CustomField>
    <fullName>ReasonForDeclination__c</fullName>
    <label>Reason For Declination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ReasonForDeclination</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FactoringResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ReasonForDeclination.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BAD_SCORING</fullName>
    </customValue>
    <customValue>
        <fullName>EXCLUDED_SECTOR</fullName>
    </customValue>
    <customValue>
        <fullName>TURNOVER_TOO_LARGE</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN_SME</fullName>
    </customValue>
    <masterLabel>Reason For Declination</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMBIGUOUS</fullName>
    </customValue>
    <customValue>
        <fullName>CONDITIONAL_ACCEPTANCE</fullName>
    </customValue>
    <customValue>
        <fullName>ERROR</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>WAIT</fullName>
        <default>true</default>
        <label>WAIT</label>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AXAFactoringServiceDoValidation.cls
public with sharing class AXAFactoringServiceDoValidation {
    @AuraEnabled
    public static void doValidation(String requestId) {
        doValidationInternal(new List<String>{requestId});
    }


    @InvocableMethod(label='AXA Factoring Service - Validation' description='')
    public static void doValidation(List<String> requestIds) {
        doValidationInternal(requestIds);
    }

    @future(callout=true)
    private static void doValidationInternal(List<String> requestIds){
        List<FactoringResponse__c> results = new List<FactoringResponse__c>();
        List<FactoringRequest__c> requests = new List<FactoringRequest__c>();
        for(FactoringRequest__c req : [SELECT Id, Contact__c, Account__c, RequestId__c FROM FactoringRequest__c WHERE RequestID__c in :requestIds OR Id in :requestIds]){
            AXAScoringBusinessActsDe.validatingResult result = AXAFactoringService.validate(req.RequestId__c);
            results.add(
                new FactoringResponse__c(
                    FactoringRequest__c = req.Id, 
                    Contact__c = req.Contact__c, 
                    Account__c = req.Account__c,
                    Condition__c = result.condition,
                    PurchaseLimit__c = result.purchaseLimit,
                    ReasonForDeclination__c = result.reasonForDeclination,
                    Status__c = result.status));
            requests.add(
                new FactoringRequest__c(Id = req.Id, Status__c = result.status));
        }
        insert results;
        update requests;
    }
}