force-app/main/default/objects/FactoringRequest__c/FactoringRequest__c.object-meta.xml
<CustomObject>
    <label>Factoring Request</label>
    <nameField>
        <displayFormat>FREQ#{000000}</displayFormat>
        <label>Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factoring Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FactoringRequest__c/fields/DirectorateNumber__c.field-meta.xml
<CustomField>
    <fullName>DirectorateNumber__c</fullName>
    <label>Directorate #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/EntitledToDeductVAT__c.field-meta.xml
<CustomField>
    <fullName>EntitledToDeductVAT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entitled To Deduct VAT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/Fon__c.field-meta.xml
<CustomField>
    <fullName>Fon__c</fullName>
    <label>Fon</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/GrossTurnover__c.field-meta.xml
<CustomField>
    <fullName>GrossTurnover__c</fullName>
    <label>Gross Turnover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/LegalForm__c.field-meta.xml
<CustomField>
    <fullName>LegalForm__c</fullName>
    <label>Legal Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/LegalRepresentative__c.field-meta.xml
<CustomField>
    <fullName>LegalRepresentative__c</fullName>
    <label>Legal Representative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/MobileFon__c.field-meta.xml
<CustomField>
    <fullName>MobileFon__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/RequestID__c.field-meta.xml
<CustomField>
    <fullName>RequestID__c</fullName>
    <externalId>true</externalId>
    <label>Request ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactoringRequest__c/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <label>VAT #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMBIGUOUS</fullName>
    </customValue>
    <customValue>
        <fullName>CONDITIONAL_ACCEPTANCE</fullName>
    </customValue>
    <customValue>
        <fullName>ERROR</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>WAIT</fullName>
        <default>true</default>
        <label>WAIT</label>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AXAFactoringServiceDoRequest.cls
global with sharing class AXAFactoringServiceDoRequest {
    @InvocableMethod(label='AXA Factoring Service - Request' description='')
    global static void doRequest(List<Id> factoringReqIds) {
        doRequestInternal(factoringReqIds);
    }

    @future(callout=true)
    private static void doRequestInternal(List<Id> factoringReqIds){
        List<FactoringRequest__c> results = new List<FactoringRequest__c>();
        for(FactoringRequest__c req : [SELECT Id, CompanyName__c, FirstName__c, LastName__c, City__c, DirectorateNumber__c, Email__c, EntitledToDeductVAT__c, Fax__c, Fon__c, LegalForm__c, LegalRepresentative__c, MobileFon__c, Street__c, StreetNumber__c, VATNumber__c, Zip__c, GrossTurnover__c FROM FactoringRequest__c WHERE Id in :factoringReqIds]){
            String requestId = AXAFactoringService.request(req);
            results.add(new FactoringRequest__c(Id = req.Id, RequestId__c = requestId, Status__c = AXAFactoringService.ResultStatus.WAIT.name()));
        }
        update results;
    }
}